<!DOCTYPE html>
<html lang="pt-br">
<head>
<meta charset="UTF-8">
<title>Painel de Estudos PHP</title>
<link rel="stylesheet" href="style.css">
</head>

<body>

<div class="container">

<h1>Painel de Estudos PHP</h1>

<div class="menu">

<a href="strings.php">Funções de Strings</a>

<a href="numeros.php">Funções Numéricas</a>

<a href="arrays.php">Funções de Array</a>

<a href="datas.php">Funções de Data</a>

</div>

</div>

</body>
</html>